root_dir: "D:/duong_huy_ct7/deepfake-data"
save_dir: "checkpoints"
image_size: 224
batch_size: 32
num_workers: 4
epochs: 30
lr: 0.0001
weight_decay: 1.0e-4
alpha: 1.0
r: 0.1
patience_scheduler: 2
early_stopping_patience: 5
num_classes: 2
model_name: "efficientnet_b4"
pretrained: true
seed: 42
original_upsample_factor: 2
dropout_rate: 0.5
mixup_alpha: 0.2
